# Generated by Django 5.2.16 on 2026-07-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="provider",
            field=models.CharField(default="stripe", max_length=30),
        ),
    ]
