# Generated by Django 5.2.16 on 2026-07-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_domain_team_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='custom_domain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='core.customdomain'),
        ),
    ]
