# Generated by Django 5.2.16 on 2026-07-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_custom_domain_to_shortlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='mp_payment_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='purchase_status',
            field=models.CharField(blank=True, choices=[('purchase_pending', 'Pago pendiente'), ('purchase_paid', 'Pagado, registrando'), ('purchase_registered', 'Registrado'), ('purchase_failed', 'Fallo en registro')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='source',
            field=models.CharField(choices=[('byod', 'Dominio propio'), ('purchased', 'Comprado via plataforma')], default='byod', max_length=20),
        ),
    ]
